instances:
  - name: kubemaster
    type: master
    count: 1
    settings:
      box: "centos/7"
      cpus: 2
      memory: 1024
      disk_size: "20GB"
      vbguest_auto_update: false
      box_check_update: false
      network:
        private_network_ip: "192.168.33.100"
  - name: kubenode
    type: node
    count: 1
    settings:
      box: "centos/7"
      cpus: 2
      memory: 1024
      disk_size: "20GB"
      vbguest_auto_update: false
      box_check_update: false
      network:
        private_network_ip: "192.168.33.200"