instances:
  - name: "kubemaster"
    type: "master"
    count: 1
    settings:
      box: "centos/7"
      box_version: "1804.02"
      box_check_update: false
      cpus: 2
      memory: 2048
      disk_size: "20GB"
      vbguest_auto_update: false
      cgroup_driver: "cgroupfs"
      network:
        private_network_ip: "192.168.33.100"
        cert_extra_sans: "peon,peasant,192.168.0.18"
        pod_network_cidr: "192.168.0.0/16"
        #ports:
        #- send: 6443
        #  to: 6443
  - name: "kubeworker"
    type: "worker"
    count: 1
    settings:
      box: "centos/7"
      box_version: "1804.02"
      box_check_update: false
      cpus: 2
      memory: 2048
      disk_size: "20GB"
      vbguest_auto_update: false
      cgroup_driver: "cgroupfs"
      network:
        private_network_ip: "192.168.33.200"
