---
- name: upgrade all packages
  package:
    name: "*"
    state: latest

- include_tasks: resolvconf.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install common packages
  package:
    name: "{{ common_packages }}"
    state: latest
