---
- name: reset all kubeadm installed state
  command: kubeadm reset --force
  ignore_errors: true

- name: ensure kubelet is running
  service:
    name: kubelet
    state: started
    enabled: yes

