---
- debug: msg="reset k8s state"
  notify:
    - reset all kubeadm installed state

- stat:
    path: /vagrant/join-command.sh
  register: join_command

- name: join cluster 1/2
  script: join_command.stat.path
  when: join_command.stat.isFile is defined and join_command.stat.isFile
  ignore_errors: true

- name: join cluster 2/2
  command: '{{ hostvars[groups["masters"][0]]["kubeadm_join_cmd"] }}'
  when: join_command.stat.isFile is undefined
  ignore_errors: true
  register: join_command_by_facts

- name: join cluster part 2 - copy the join command to server location 1/3
  copy: src=/vagrant/join-command dest=/tmp/join-command.sh mode=0777
  when: join_command_by_facts.rc != 0

- debug: msg="join cluster part 2 - call kubeadm reset 2/3"
  when: join_command_by_facts.rc != 0
  notify:
    - reset all kubeadm installed state
    - ensure kubelet is running

- name: join cluster part 2 - join the node to cluster 3/3
  command: sh /tmp/join-command.sh
  become: yes
  when: join_command_by_facts.rc != 0
