---
- name:  reset all kubeadm installed state
  command: kubeadm reset --force
  ignore_errors: true

- stat:
    path: /vagrant/join-command.sh
  register: join_command

- name: join cluster
  script: join_command.stat.path
  when: join_command.stat.isFile is defined and join_command.stat.isFile
  