---
- include_tasks: centos.yml
  when: ansible_facts['distribution'] == 'CentOS'

- include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: disable SWAP since kubernetes can't work with swap enabled (1/2)
  command: "swapoff -a"

- name: disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: install required packages
  package:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- include_tasks: configure-network.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: ensure kubelet is running
  service:
    name: kubelet
    state: started
    enabled: yes

- name: update ip6tables settings
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: update iptables settings
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
