---
- hosts: "masters,workers"
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - epel-repository
    - role: common
      when: skip_role_common is undefined
    - docker
    - kube

- hosts: masters
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - role: kube-master

- hosts: workers
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - role: kube-worker
