---
- hosts: "masters,workers"
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - role: epel-repository
      when: ansible_facts['distribution'] == 'CentOS'
    - role: common
      when: skip_role_common is undefined
    - role: docker
    - role: kube

- hosts: masters
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - role: kube-master

- hosts: workers
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - role: kube-worker
